[package]
name = "agora-rpc"
description = "JSON-RPC / REST access layer for Agora Network"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
agora-types = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
