[package]
name = "agora-node"
description = "Agora Network full node entrypoint"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "agora-node"
path = "src/main.rs"

[dependencies]
agora-types = { workspace = true }
agora-crypto = { workspace = true }
agora-consensus = { workspace = true }
agora-state-machine = { workspace = true, features = ["rocksdb"] }
agora-p2p = { workspace = true }
agora-rpc = { workspace = true }
borsh = { workspace = true }
hex = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3"
