export {
  COMMUNITY_SCHEMA_VERSION,
  DATA_SOURCES,
  GOVERNANCE_AREA_IDS,
  GUILD_KINDS,
  MISSION_STATES,
  REPUTATION_CATEGORIES,
  type AcademyCatalog,
  type AcademyCourse,
  type AcademyLesson,
  type AcademyProgress,
  type Badge,
  type Bounty,
  type CachedDoc,
  type CommunityBundle,
  type CommunityEvent,
  type CommunityProposal,
  type CommunityTreasuryRow,
  type Contribution,
  type DataSource,
  type DirectoryEntry,
  type EcosystemSnapshot,
  type ForumPost,
  type ForumReply,
  type ForumReport,
  type GovernanceArea,
  type GovernanceAreaId,
  type Grant,
  type Guild,
  type GuildKind,
  type Hub,
  type MerchantProfile,
  type Mission,
  type MissionState,
  type NotificationPrefs,
  type PrivatePassportProfile,
  type ProposalBinding,
  type PublicPassport,
  type ReputationCategory,
  type ReputationScores,
} from "./types.ts";
export {
  encodeAgoraQr,
  parseAgoraQr,
  assertPaymentPreview,
  QR_KINDS,
  QR_VERSION,
  type AgoraQrPayload,
  type QrKind,
  type QrParseResult,
  type QrPreview,
} from "./qr.ts";
export {
  antiSybilDecision,
  assertCommunitySpendAllowed,
  createRateLimiter,
  createSessionChallenge,
  exportCommunitySession,
  issueSession,
  sessionIsLive,
  signSessionChallenge,
  verifySessionSignature,
  SESSION_DOMAIN,
  SESSION_TTL_MS,
  type CommunitySession,
  type SessionChallenge,
  type WalletMode,
} from "./session.ts";
export {
  applyReputationEvent,
  emptyScores,
  overallScore,
  splitPassport,
  transferBadge,
  REPUTATION_EVENTS,
  type ReputationEvent,
  type ReputationEventKind,
} from "./reputation.ts";
export { transitionMission } from "./missions.ts";
export {
  GOVERNANCE_AREAS,
  areaById,
  proposalBadge,
  voteEligibility,
} from "./governance.ts";
export {
  DRC_PAY_STEPS,
  advanceDrcPay,
  assertConfirmShown,
  broadcastDrcPay,
  signDrcPayIntent,
  type DrcPayReceipt,
  type DrcPayStep,
  type MerchantCheck,
} from "./pay.ts";
export {
  COMMUNITY_CACHE_KEY,
  defaultNotificationPrefs,
  emptyCache,
  loadCache,
  memoryCacheStorage,
  notificationBody,
  presentCached,
  recordLessonProgress,
  saveCache,
  type CacheStorage,
  type CommunityCacheBlob,
  type OfflineView,
} from "./cache.ts";
export {
  DEMO_ADDRESS,
  communityFixtures,
  demoPassport,
  demoPrivateProfile,
  merchantForAddress,
  reportForumPost,
  searchHubs,
} from "./fixtures.ts";
export {
  createCommunityClient,
  preferChainTreasuries,
  type CommunityClient,
} from "./client.ts";
