// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Packed accepted/rejected bits for transactions in one blue block.
 *
 * Bit `i` corresponds to `block.transactions[i]`. Bits are packed little-endian
 * within each byte (bit 0 of byte 0 = transaction index 0).
 */
export type AcceptanceBitmap = { len: number, bytes: Array<number>, };
