// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { NativeAssetId } from "./NativeAssetId";

/**
 * Signed account-to-account transfer for OVL or DRC.
 */
export type AccountTransfer = { version: number, asset: NativeAssetId, from: Address, to: Address, amount: Amount,
/**
 * Explicit same-asset fee (credited to staking reward pool when Accepted).
 */
fee: Amount,
/**
 * Sender account nonce (must match current on-chain nonce).
 */
nonce: bigint, public_key: Array<number>, signature: Array<number>, };
