// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcAccountSequenceSelector } from "./DrcAccountSequenceSelector";
import type { DrcMultisignAuth } from "./DrcMultisignAuth";
import type { NativeAssetId } from "./NativeAssetId";

/**
 * Signed account-to-account transfer for OVL or DRC.
 */
export type AccountTransfer = { version: number, asset: NativeAssetId, from: Address, to: Address, amount: Amount,
/**
 * Explicit same-asset fee (credited to staking reward pool when Accepted).
 */
fee: Amount,
/**
 * Sender account nonce (must match current on-chain nonce).
 */
nonce: bigint,
/**
 * Explicit nonce/ticket selector for DRC v3+ (required when `version >= 3`).
 */
account_sequence: DrcAccountSequenceSelector | null, public_key: Array<number>, signature: Array<number>, multisign: DrcMultisignAuth | null, };
