// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bech32-ready raw payload for a secp256k1-derived address (20-byte hash of pubkey).
 */
export type Address = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];
