// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Base units of AGORA (8 decimal places). Prefer this over raw `u64` at API boundaries.
 */
export type Amount = bigint;
