// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { NativeAssetId } from "./NativeAssetId";

/**
 * Trident UTXO/account output shape (asset-explicit).
 *
 * Existing v2 `TxOut` remains TLT-implicit for the frozen testnet wire format.
 * Phase 2 state transition consumes this type (or a versioned transaction body).
 */
export type AssetTxOut = { asset: NativeAssetId, value: Amount, address: Address, };
