// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "./Hash";

/**
 * Block header for Agora's BlockDAG tips.
 *
 * Multiple parents enable parallel block production; GHOSTDAG later imposes order.
 */
export type BlockHeader = { version: number, parents: Array<Hash>, timestamp_ms: bigint, bits: number, nonce: bigint, tx_root: Hash, };
