// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountTransfer } from "./AccountTransfer";
import type { BlockHeader } from "./BlockHeader";
import type { DataCommitmentAuthorization } from "./DataCommitmentAuthorization";
import type { DrcAccountPolicyTx } from "./DrcAccountPolicyTx";
import type { DrcCheckCancelTx } from "./DrcCheckCancelTx";
import type { DrcCheckCashTx } from "./DrcCheckCashTx";
import type { DrcCheckCreateTx } from "./DrcCheckCreateTx";
import type { DrcDepositPreauthTx } from "./DrcDepositPreauthTx";
import type { DrcEscrowCancelTx } from "./DrcEscrowCancelTx";
import type { DrcEscrowCreateTx } from "./DrcEscrowCreateTx";
import type { DrcEscrowFinishTx } from "./DrcEscrowFinishTx";
import type { DrcIssuedAssetPolicySetTx } from "./DrcIssuedAssetPolicySetTx";
import type { DrcIssuedClawbackTx } from "./DrcIssuedClawbackTx";
import type { DrcIssuedTransferTx } from "./DrcIssuedTransferTx";
import type { DrcMultisignBlockAttachment } from "./DrcMultisignBlockAttachment";
import type { DrcPaymentChannelClaimTx } from "./DrcPaymentChannelClaimTx";
import type { DrcPaymentChannelCloseTx } from "./DrcPaymentChannelCloseTx";
import type { DrcPaymentChannelCreateTx } from "./DrcPaymentChannelCreateTx";
import type { DrcPaymentChannelFundTx } from "./DrcPaymentChannelFundTx";
import type { DrcPaymentTx } from "./DrcPaymentTx";
import type { DrcRegularKeyTx } from "./DrcRegularKeyTx";
import type { DrcSignerListTx } from "./DrcSignerListTx";
import type { DrcTicketCreateTx } from "./DrcTicketCreateTx";
import type { DrcTrustLineIssuerControlTx } from "./DrcTrustLineIssuerControlTx";
import type { DrcTrustLineSetTx } from "./DrcTrustLineSetTx";
import type { OvlExecutionTx } from "./OvlExecutionTx";
import type { SignedStakeTx } from "./SignedStakeTx";
import type { TltCovenantTx } from "./TltCovenantTx";
import type { Transaction } from "./Transaction";

/**
 * Full Trident body with an OVL-only execution lane.
 *
 * Every `drc_*` field is a closed, protocol-native state-machine lane. DRC
 * has no bytecode, VM, deploy, contract-call, or generic execution lane.
 */
export type Block = { header: BlockHeader,
/**
 * TLT UTXO lane (coinbase + transfers).
 */
transactions: Array<Transaction>,
/**
 * OVL/DRC liquid account transfers (Trident).
 */
account_transfers: Array<AccountTransfer>,
/**
 * OVL/DRC staking ops (Trident).
 */
stake_ops: Array<SignedStakeTx>,
/**
 * Signed, gas-metered OVL execution envelopes.
 */
ovl_executions: Array<OvlExecutionTx>,
/**
 * Signed native DRC payments with routing metadata.
 */
drc_payments: Array<DrcPaymentTx>,
/**
 * Provenance-bound, operator-authorized data commitments.
 */
data_commitments: Array<DataCommitmentAuthorization>,
/**
 * Owner-authorized, contract-free DRC recipient-policy operations.
 */
drc_account_policies: Array<DrcAccountPolicyTx>,
/**
 * Owner-authorized, address-based DRC deposit preauthorizations.
 */
drc_deposit_preauths: Array<DrcDepositPreauthTx>,
/**
 * Owner-authorized DRC regular-key rotation operations.
 */
drc_regular_keys: Array<DrcRegularKeyTx>,
/**
 * Owner-authorized DRC weighted signer-list operations.
 */
drc_signer_lists: Array<DrcSignerListTx>,
/**
 * Owner-authorized DRC ticket creation (one ticket per operation).
 */
drc_ticket_creates: Array<DrcTicketCreateTx>,
/**
 * Owner-authorized native DRC escrow creates.
 */
drc_escrow_creates: Array<DrcEscrowCreateTx>,
/**
 * Submitter-authorized native DRC escrow finishes.
 */
drc_escrow_finishes: Array<DrcEscrowFinishTx>,
/**
 * Submitter-authorized native DRC escrow cancels.
 */
drc_escrow_cancels: Array<DrcEscrowCancelTx>,
/**
 * Owner-authorized native DRC check creates.
 */
drc_check_creates: Array<DrcCheckCreateTx>,
/**
 * Destination-authorized native DRC check cash (exact value).
 */
drc_check_cashes: Array<DrcCheckCashTx>,
/**
 * Authorized native DRC check cancels.
 */
drc_check_cancels: Array<DrcCheckCancelTx>,
/**
 * Owner-authorized native DRC payment channel creates.
 */
drc_payment_channel_creates: Array<DrcPaymentChannelCreateTx>,
/**
 * Owner-authorized native DRC payment channel funds.
 */
drc_payment_channel_funds: Array<DrcPaymentChannelFundTx>,
/**
 * Destination-authorized native DRC payment channel claims.
 */
drc_payment_channel_claims: Array<DrcPaymentChannelClaimTx>,
/**
 * Authorized native DRC payment channel closes.
 */
drc_payment_channel_closes: Array<DrcPaymentChannelCloseTx>,
/**
 * Holder-authorized issuer-scoped trust line set/delete operations.
 */
drc_trust_line_sets: Array<DrcTrustLineSetTx>,
/**
 * Exact issued-value transfers (issue/redeem/holder transfer).
 */
drc_issued_transfers: Array<DrcIssuedTransferTx>,
/**
 * Issuer-scoped asset policy (auth/freeze/clawback flags).
 */
drc_issued_asset_policy_sets: Array<DrcIssuedAssetPolicySetTx>,
/**
 * Issuer line authorize/freeze/deep-freeze controls.
 */
drc_trust_line_issuer_controls: Array<DrcTrustLineIssuerControlTx>,
/**
 * Issuer exact clawback from one holder line.
 */
drc_issued_clawbacks: Array<DrcIssuedClawbackTx>,
/**
 * Detached, body-root-committed DRC multisign authorization (consensus lane).
 */
drc_multisign_attachments: Array<DrcMultisignBlockAttachment>,
/**
 * TLT covenant spends. Absent from the wire when empty so v1 block bytes stay frozen.
 */
tlt_covenants: Array<TltCovenantTx>, };
