// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountTransfer } from "./AccountTransfer";
import type { BlockHeader } from "./BlockHeader";
import type { OvlExecutionTx } from "./OvlExecutionTx";
import type { SignedStakeTx } from "./SignedStakeTx";
import type { Transaction } from "./Transaction";

/**
 * Full block: header + multi-lane body (TLT UTXO + OVL/DRC account/stake + OVL execution).
 */
export type Block = { header: BlockHeader,
/**
 * TLT UTXO lane (coinbase + transfers).
 */
transactions: Array<Transaction>,
/**
 * OVL/DRC liquid account transfers (Trident).
 */
account_transfers: Array<AccountTransfer>,
/**
 * OVL/DRC staking ops (Trident).
 */
stake_ops: Array<SignedStakeTx>,
/**
 * Signed, gas-metered OVL execution envelopes.
 */
ovl_executions: Array<OvlExecutionTx>, };
