// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockHeader } from "./BlockHeader";
import type { Transaction } from "./Transaction";

/**
 * Full block: header + transactions.
 */
export type Block = { header: BlockHeader, transactions: Array<Transaction>, };
