// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "./Hash";

/**
 * Consensus-relevant checkpoint identity (domain-separated signing body).
 */
export type CheckpointBody = { chain_id: string, genesis_hash: Hash, consensus_policy_hash: Hash, state_transition_version: string, blue_score: bigint, block_hash: Hash, state_root: Hash, validator_epoch: bigint, };
