// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { CheckpointBody } from "./CheckpointBody";
import type { NativeAssetId } from "./NativeAssetId";

/**
 * One validator's attestation over a checkpoint body.
 */
export type CheckpointAttestation = { body: CheckpointBody, 
/**
 * Which validator set this signature belongs to.
 */
set: NativeAssetId, validator: Address, public_key: Array<number>, signature: Array<number>, };
