// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire grant kind. Borsh order matches `agora_governance::GrantKind`.
 */
export type CommunityGrantKind = "Micro" | "Milestone" | "Bounty" | "Retroactive";
