// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { Hash } from "./Hash";

/**
 * Milestone shape committed at grant registration (always pending on apply).
 */
export type CommunityGrantMilestone = { index: number, amount: Amount, deliverable_hash: Hash, };
