// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Append-only source discriminant for explicitly non-canonical producer data.
 */
export type DataCommitmentSource = "AgoraLayersOvolosBatchLab";
