// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { DataAvailabilityCommitment } from "./DataAvailabilityCommitment";

/**
 * Signed operator authorization carried in `Block::data_commitments`.
 *
 * `replay_nonce` is cryptographically bound here and enforced atomically by
 * the state transition. Inclusion burns [`DA_INCLUSION_FEE_TLT`] from the
 * operator's TLT UTXOs. The DA fingerprint is the mesh bind, not a fee gate.
 */
export type DataCommitmentAuthorization = { version: number, operator: Address, replay_nonce: bigint, commitment: DataAvailabilityCommitment, public_key: Array<number>, signature: Array<number>, };
