// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { DataAvailabilityCommitment } from "./DataAvailabilityCommitment";

/**
 * Signed operator authorization carried in `Block::data_commitments`.
 *
 * `replay_nonce` is cryptographically bound here and enforced atomically by
 * the state transition. This type alone is not replay protection and remains
 * deliberately unavailable through standalone RPC submission.
 */
export type DataCommitmentAuthorization = { version: number, operator: Address, replay_nonce: bigint, commitment: DataAvailabilityCommitment, public_key: Array<number>, signature: Array<number>, };
