// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataCommitmentSource } from "./DataCommitmentSource";
import type { Hash } from "./Hash";

/**
 * Deterministic commitment to one historical `agora-layers` Ovolos batch.
 *
 * This commits integrity and provenance. It does not prove that the underlying
 * transaction data is available and does not make lab balances canonical.
 */
export type DataAvailabilityCommitment = { version: number, source: DataCommitmentSource, source_chain_id: string, source_genesis_hash: Hash, batch_id: Hash, sequence: bigint, prev_state_root: Hash, post_state_root: Hash, tx_merkle_root: Hash, tx_count: number, source_timestamp_ms: bigint, };
