// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { DataAvailabilityCommitment } from "./DataAvailabilityCommitment";

/**
 * Signed operator authorization that a future versioned L1 transaction can carry.
 *
 * `replay_nonce` is cryptographically bound here. A future state transition
 * must still enforce and persist it atomically; this type alone is not replay
 * protection and is deliberately not exposed through RPC.
 */
export type DataCommitmentAuthorization = { version: number, operator: Address, replay_nonce: bigint, commitment: DataAvailabilityCommitment, public_key: Array<number>, signature: Array<number>, };
