// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";

/**
 * Canonical installed regular key for one owner account.
 */
export type DrcAccountRegularKey = { version: number, owner: Address, regular_key: Address, };
