// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcAccountPolicyAction } from "./DrcAccountPolicyAction";
import type { DrcAccountSequenceSelector } from "./DrcAccountSequenceSelector";
import type { DrcMultisignAuth } from "./DrcMultisignAuth";

/**
 * Signed DRC account-policy operation.
 */
export type DrcAccountPolicyTx = { version: number, account: Address, action: DrcAccountPolicyAction,
/**
 * Explicit DRC fee credited to the DRC validator reward pool on acceptance.
 */
fee: Amount,
/**
 * Shared DRC nonce used by transfers, stake ops, policies, preauths, and payments.
 */
nonce: bigint, account_sequence: DrcAccountSequenceSelector | null, public_key: Array<number>, signature: Array<number>, multisign: DrcMultisignAuth | null, };
