// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";

/**
 * Canonical persisted ticket set for one owner (sorted sequences, capped).
 */
export type DrcAccountTickets = { version: number, owner: Address, 
/**
 * Sorted strictly increasing ticket sequences.
 */
sequences: Array<bigint>, };
