// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcAccountPolicyAction } from "./DrcAccountPolicyAction";

/**
 * Signed DRC account-policy operation.
 */
export type DrcAccountPolicyTx = { version: number, account: Address, action: DrcAccountPolicyAction,
/**
 * Explicit DRC fee credited to the DRC validator reward pool on acceptance.
 */
fee: Amount,
/**
 * Shared DRC account nonce used by transfers, stake ops, payments, and policies.
 */
nonce: bigint, public_key: Array<number>, signature: Array<number>, };
