// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The only DRC account-policy actions activated in this bounded slice.
 */
export type DrcAccountPolicyAction = "set_require_destination_tag" | "clear_require_destination_tag";
