// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { DrcOperation } from "./DrcOperation";
import type { DrcOperationKind } from "./DrcOperationKind";
import type { Hash } from "./Hash";

export type DrcAcceptedOperationReceipt = { version: number, operation_id: Hash, historical_transaction_id: Hash, owner: Address, kind: DrcOperationKind, canonical_block_id: Hash, application_blue_score: bigint | null, operation: DrcOperation, affected_object_ids: Array<Hash>, };
