// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical recipient policy. Missing state is exactly [`Self::default`].
 */
export type DrcAccountPolicy = { version: number, require_destination_tag: boolean,
/**
 * Incoming non-self payments require an address preauthorization when enabled.
 */
deposit_auth_required: boolean,
/**
 * When set, the owner master secp256k1 key cannot authorize DRC account operations.
 */
master_key_disabled: boolean, };
