// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { DrcSignerListEntry } from "./DrcSignerListEntry";

/**
 * Canonical installed signer list for one owner account.
 */
export type DrcAccountSignerList = { version: number, owner: Address, quorum: number, entries: Array<DrcSignerListEntry>, };
