// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical recipient policy. Missing state is exactly [`Self::default`].
 */
export type DrcAccountPolicy = { version: number, require_destination_tag: boolean, };
