// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrcAccountSequence } from "./DrcAccountSequence";

export type DrcAccountSequenceSelector = { kind: DrcAccountSequence, value: bigint, };
