// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssuedAssetId } from "./IssuedAssetId";

/**
 * One side of a book. Native DRC is never an [`IssuedAssetId`].
 */
export type DrcBookAsset = { "type": "native_drc" } | { "type": "issued" } & IssuedAssetId;
