// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcAccountSequenceSelector } from "./DrcAccountSequenceSelector";
import type { DrcMultisignAuth } from "./DrcMultisignAuth";
import type { Hash } from "./Hash";

export type DrcCheckCreateTx = { version: number, owner: Address, destination: Address, amount: Amount, fee: Amount, destination_tag: number | null, source_tag: number | null, invoice_id: Hash, expires_after_blue_score: bigint | null, nonce: bigint, account_sequence: DrcAccountSequenceSelector | null, public_key: Array<number>, signature: Array<number>, multisign: DrcMultisignAuth | null, };
