// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recipient-selected action for one source account.
 */
export type DrcDepositPreauthAction = "authorize" | "unauthorize";
