// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcAccountSequenceSelector } from "./DrcAccountSequenceSelector";
import type { DrcDepositPreauthAction } from "./DrcDepositPreauthAction";
import type { DrcMultisignAuth } from "./DrcMultisignAuth";

/**
 * Owner-signed operation that grants or revokes one address-based preauthorization.
 */
export type DrcDepositPreauthTx = { version: number, 
/**
 * Recipient that owns and controls the preauthorization record.
 */
owner: Address, action: DrcDepositPreauthAction, 
/**
 * Source account allowed to deposit to `owner` while DepositAuth is enabled.
 */
authorized_source: Address, 
/**
 * Explicit DRC fee credited to the DRC validator reward pool on acceptance.
 */
fee: Amount, 
/**
 * Shared DRC nonce used by transfers, stake ops, policies, preauths, and payments.
 */
nonce: bigint, account_sequence: DrcAccountSequenceSelector | null, public_key: Array<number>, signature: Array<number>, multisign: DrcMultisignAuth | null, };
