// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcEscrowOutcome } from "./DrcEscrowOutcome";
import type { Hash } from "./Hash";

export type DrcEscrowReceipt = { version: number, escrow_id: Hash, outcome: DrcEscrowOutcome, owner: Address, recipient: Address, amount: Amount, destination_tag: number | null, source_tag: number | null, invoice_id: Hash, settlement_blue_score: bigint, settlement_tx_id: Hash, };
