// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { Hash } from "./Hash";

export type DrcEscrowLive = { version: number, escrow_id: Hash, owner: Address, recipient: Address, amount: Amount, destination_tag: number | null, source_tag: number | null, invoice_id: Hash, finish_after_blue_score: bigint | null, cancel_after_blue_score: bigint | null, create_blue_score: bigint, };
