// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssuedAssetId } from "./IssuedAssetId";

export type DrcIssuedAssetPolicyLive = { version: number, asset: IssuedAssetId, require_auth: boolean, global_freeze: boolean, no_freeze: boolean, clawback_enabled: boolean, };
