// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcAccountSequenceSelector } from "./DrcAccountSequenceSelector";
import type { DrcMultisignAuth } from "./DrcMultisignAuth";
import type { Hash } from "./Hash";
import type { IssuedAmount } from "./IssuedAmount";
import type { IssuedCurrencyCode } from "./IssuedCurrencyCode";

export type DrcIssuedTransferTx = { version: number, sender: Address, recipient: Address, issuer: Address, currency: IssuedCurrencyCode, amount: IssuedAmount, fee: Amount, destination_tag: number | null, source_tag: number | null, invoice_id: Hash, nonce: bigint, account_sequence: DrcAccountSequenceSelector | null, public_key: Array<number>, signature: Array<number>, multisign: DrcMultisignAuth | null, };
