// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssuedAmount } from "./IssuedAmount";
import type { IssuedAssetId } from "./IssuedAssetId";

export type DrcIssuerLiability = { version: number, asset: IssuedAssetId, outstanding: IssuedAmount, };
