// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Hash } from "./Hash";
import type { IssuedAmount } from "./IssuedAmount";
import type { IssuedAssetId } from "./IssuedAssetId";

export type DrcIssuedTransferReceipt = { version: number, transfer_tx_id: Hash, asset: IssuedAssetId, sender: Address, recipient: Address, amount: IssuedAmount, source_tag: number | null, destination_tag: number | null, settlement_blue_score: bigint, };
