// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrcIssuedAssetPolicyAction } from "./DrcIssuedAssetPolicyAction";
import type { Hash } from "./Hash";
import type { IssuedAssetId } from "./IssuedAssetId";

export type DrcIssuedAssetPolicyReceipt = { version: number, policy_set_tx_id: Hash, asset: IssuedAssetId, action: DrcIssuedAssetPolicyAction, settlement_blue_score: bigint, };
