// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Hash } from "./Hash";
import type { IssuedAmount } from "./IssuedAmount";
import type { IssuedAssetId } from "./IssuedAssetId";

export type DrcIssuedClawbackReceipt = { version: number, clawback_tx_id: Hash, asset: IssuedAssetId, holder: Address, amount: IssuedAmount, settlement_blue_score: bigint, };
