// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { DrcAccountPolicy } from "./DrcAccountPolicy";
import type { DrcAccountRegularKey } from "./DrcAccountRegularKey";
import type { DrcAccountSignerList } from "./DrcAccountSignerList";
import type { DrcAccountTickets } from "./DrcAccountTickets";
import type { DrcCheckLive } from "./DrcCheckLive";
import type { DrcDepositPreauth } from "./DrcDepositPreauth";
import type { DrcEscrowLive } from "./DrcEscrowLive";
import type { DrcIssuedAssetPolicyLive } from "./DrcIssuedAssetPolicyLive";
import type { DrcPaymentChannelLive } from "./DrcPaymentChannelLive";
import type { DrcTrustLineLive } from "./DrcTrustLineLive";

export type DrcLedgerObject = { "type": "account_policy", "value": { account: Address, policy: DrcAccountPolicy, } } | { "type": "deposit_preauthorization", "value": DrcDepositPreauth } | { "type": "regular_key", "value": DrcAccountRegularKey } | { "type": "signer_list", "value": DrcAccountSignerList } | { "type": "ticket_set", "value": DrcAccountTickets } | { "type": "escrow", "value": DrcEscrowLive } | { "type": "check", "value": DrcCheckLive } | { "type": "payment_channel", "value": DrcPaymentChannelLive } | { "type": "trust_line", "value": DrcTrustLineLive } | { "type": "issued_asset_policy", "value": DrcIssuedAssetPolicyLive };
