// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { DrcLedgerObjectDescriptor } from "./DrcLedgerObjectDescriptor";
import type { DrcLedgerObjectKind } from "./DrcLedgerObjectKind";

export type DrcLedgerObjectPage = { owner: Address, kind: DrcLedgerObjectKind | null, objects: Array<DrcLedgerObjectDescriptor>, next_cursor: string | null, };
