// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Hash } from "./Hash";
import type { IssuedAssetId } from "./IssuedAssetId";

export type DrcLedgerObjectKey = { "type": "account_policy", account: Address, } | { "type": "deposit_preauthorization", owner: Address, authorized_source: Address, } | { "type": "regular_key", owner: Address, } | { "type": "signer_list", owner: Address, } | { "type": "ticket_set", owner: Address, } | { "type": "escrow", escrow_id: Hash, } | { "type": "check", check_id: Hash, } | { "type": "payment_channel", channel_id: Hash, } | { "type": "trust_line", holder: Address, asset: IssuedAssetId, } | { "type": "issued_asset_policy", asset: IssuedAssetId, };
