// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DrcLedgerObjectKind = "account_policy" | "deposit_preauthorization" | "regular_key" | "signer_list" | "ticket_set" | "escrow" | "check" | "payment_channel" | "trust_line" | "issued_asset_policy";
