// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { DrcLedgerObject } from "./DrcLedgerObject";
import type { DrcLedgerObjectKey } from "./DrcLedgerObjectKey";
import type { DrcLedgerObjectKind } from "./DrcLedgerObjectKind";
import type { Hash } from "./Hash";

export type DrcLedgerObjectDescriptor = { version: number, object_id: Hash, kind: DrcLedgerObjectKind, owner: Address, key: DrcLedgerObjectKey, object: DrcLedgerObject, };
