// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type tag disambiguates attachment keys across DRC operation lanes.
 */
export type DrcMultisignOperationKind = "DrcAccountTransfer" | "DrcStake" | "DrcRegularKey" | "DrcSignerList" | "DrcAccountPolicy" | "DrcDepositPreauth" | "DrcPayment" | "DrcTicketCreate" | "DrcEscrowCreate" | "DrcEscrowFinish" | "DrcEscrowCancel";
