// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { DrcMultisignEntry } from "./DrcMultisignEntry";

/**
 * Versioned detached authorization bundle. Appended to frozen single-signature Borsh encodings.
 */
export type DrcMultisignAuth = { version: number, 
/**
 * On-chain account the operation acts for (`owner` / `from` / `actor` / `account`).
 */
signing_for: Address, 
/**
 * Strictly increasing `signer` order; at most [`DRC_MULTISIGN_MAX_SIGNATURES`] entries.
 */
signatures: Array<DrcMultisignEntry>, };
