// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";

/**
 * One secp256k1 multisign participant signature (sorted by `signer` in the bundle).
 */
export type DrcMultisignEntry = { signer: Address, public_key: Array<number>, signature: Array<number>, };
