// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrcMultisignOperationKind } from "./DrcMultisignOperationKind";
import type { Hash } from "./Hash";

/**
 * Non-circular attachment lookup key: operation kind + hash(network-bound signing bytes).
 *
 * The signing commitment excludes inline `public_key`, `signature`, and multisign material
 * while binding every field in each operation's `signing_bytes_bound(chain_id, genesis)`.
 */
export type DrcMultisignAttachmentKey = { version: number, kind: DrcMultisignOperationKind, signing_commitment: Hash, };
