// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrcMultisignAttachmentKey } from "./DrcMultisignAttachmentKey";
import type { DrcMultisignAuth } from "./DrcMultisignAuth";

/**
 * One consensus attachment: canonical key + versioned auth bundle.
 */
export type DrcMultisignBlockAttachment = { version: number, key: DrcMultisignAttachmentKey, auth: DrcMultisignAuth, };
