// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountTransfer } from "./AccountTransfer";
import type { DrcAccountPolicyTx } from "./DrcAccountPolicyTx";
import type { DrcCheckCancelTx } from "./DrcCheckCancelTx";
import type { DrcCheckCashTx } from "./DrcCheckCashTx";
import type { DrcCheckCreateTx } from "./DrcCheckCreateTx";
import type { DrcDepositPreauthTx } from "./DrcDepositPreauthTx";
import type { DrcEscrowCancelTx } from "./DrcEscrowCancelTx";
import type { DrcEscrowCreateTx } from "./DrcEscrowCreateTx";
import type { DrcEscrowFinishTx } from "./DrcEscrowFinishTx";
import type { DrcIssuedAssetPolicySetTx } from "./DrcIssuedAssetPolicySetTx";
import type { DrcIssuedClawbackTx } from "./DrcIssuedClawbackTx";
import type { DrcIssuedTransferTx } from "./DrcIssuedTransferTx";
import type { DrcPaymentChannelClaimTx } from "./DrcPaymentChannelClaimTx";
import type { DrcPaymentChannelCloseTx } from "./DrcPaymentChannelCloseTx";
import type { DrcPaymentChannelCreateTx } from "./DrcPaymentChannelCreateTx";
import type { DrcPaymentChannelFundTx } from "./DrcPaymentChannelFundTx";
import type { DrcPaymentTx } from "./DrcPaymentTx";
import type { DrcRegularKeyTx } from "./DrcRegularKeyTx";
import type { DrcSignerListTx } from "./DrcSignerListTx";
import type { DrcTicketCreateTx } from "./DrcTicketCreateTx";
import type { DrcTrustLineIssuerControlTx } from "./DrcTrustLineIssuerControlTx";
import type { DrcTrustLineSetTx } from "./DrcTrustLineSetTx";
import type { SignedStakeTx } from "./SignedStakeTx";

export type DrcOperation = { "type": "account_transfer", "value": AccountTransfer } | { "type": "stake", "value": SignedStakeTx } | { "type": "payment", "value": DrcPaymentTx } | { "type": "account_policy", "value": DrcAccountPolicyTx } | { "type": "deposit_preauthorization", "value": DrcDepositPreauthTx } | { "type": "regular_key", "value": DrcRegularKeyTx } | { "type": "signer_list", "value": DrcSignerListTx } | { "type": "ticket_create", "value": DrcTicketCreateTx } | { "type": "escrow_create", "value": DrcEscrowCreateTx } | { "type": "escrow_finish", "value": DrcEscrowFinishTx } | { "type": "escrow_cancel", "value": DrcEscrowCancelTx } | { "type": "check_create", "value": DrcCheckCreateTx } | { "type": "check_cash", "value": DrcCheckCashTx } | { "type": "check_cancel", "value": DrcCheckCancelTx } | { "type": "payment_channel_create", "value": DrcPaymentChannelCreateTx } | { "type": "payment_channel_fund", "value": DrcPaymentChannelFundTx } | { "type": "payment_channel_claim", "value": DrcPaymentChannelClaimTx } | { "type": "payment_channel_close", "value": DrcPaymentChannelCloseTx } | { "type": "trust_line_set", "value": DrcTrustLineSetTx } | { "type": "issued_transfer", "value": DrcIssuedTransferTx } | { "type": "issued_asset_policy_set", "value": DrcIssuedAssetPolicySetTx } | { "type": "trust_line_issuer_control", "value": DrcTrustLineIssuerControlTx } | { "type": "issued_clawback", "value": DrcIssuedClawbackTx };
