// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrcOfferBook } from "./DrcOfferBook";
import type { DrcOfferBookCursor } from "./DrcOfferBookCursor";
import type { DrcOfferView } from "./DrcOfferView";

export type DrcOfferBookPage = { version: number, book: DrcOfferBook, offers: Array<DrcOfferView>, next_cursor: DrcOfferBookCursor | null, };
