// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrcOfferLive } from "./DrcOfferLive";

/**
 * Read model. `taker_gets_funded` is the currently deliverable remainder, not a simulated fill.
 */
export type DrcOfferView = { offer: DrcOfferLive, taker_gets_funded: bigint, expired: boolean, };
