// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcOfferCancelOutcome } from "./DrcOfferCancelOutcome";
import type { Hash } from "./Hash";

export type DrcOfferCancelReceipt = { version: number, cancel_tx_id: Hash, offer_id: Hash, submitter: Address, outcome: DrcOfferCancelOutcome, fee: Amount, settlement_blue_score: bigint, };
