// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrcBookAsset } from "./DrcBookAsset";

/**
 * Directed book: taker pays `pays` and receives `gets` from the resting offer.
 */
export type DrcOfferBook = { pays: DrcBookAsset, gets: DrcBookAsset, };
