// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { Hash } from "./Hash";

export type DrcOfferCreateReceipt = { version: number, offer_id: Hash, owner: Address, placed: boolean, fully_filled: boolean, taker_paid: bigint, taker_received: bigint, steps: number, self_cross_cancelled: number, removed_offer_ids: Array<Hash>, fee: Amount, settlement_blue_score: bigint, };
