// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrcOfferCursor } from "./DrcOfferCursor";
import type { DrcOfferView } from "./DrcOfferView";

export type DrcOfferPage = { version: number, offers: Array<DrcOfferView>, next_cursor: DrcOfferCursor | null, };
