// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcAccountSequenceSelector } from "./DrcAccountSequenceSelector";
import type { DrcBookAsset } from "./DrcBookAsset";
import type { DrcMultisignAuth } from "./DrcMultisignAuth";

export type DrcOfferCreateTx = { version: number, owner: Address, taker_pays: DrcBookAsset, taker_pays_amount: bigint, taker_gets: DrcBookAsset, taker_gets_amount: bigint, fill_mode: number, time_in_force: number, fee: Amount, expires_after_blue_score: bigint | null, nonce: bigint, account_sequence: DrcAccountSequenceSelector | null, public_key: Array<number>, signature: Array<number>, multisign: DrcMultisignAuth | null, };
