// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "./Hash";

/**
 * Book pagination cursor. Quality, sequence, and id are the committed sort key.
 */
export type DrcOfferBookCursor = { gets_original: bigint, pays_original: bigint, book_sequence: bigint, offer_id: Hash, };
