// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "./Hash";

/**
 * Account-offer pagination cursor. It is the last returned offer id, not a fill.
 */
export type DrcOfferCursor = { offer_id: Hash, };
