// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { DrcBookAsset } from "./DrcBookAsset";
import type { Hash } from "./Hash";

export type DrcOfferLive = { version: number, offer_id: Hash, owner: Address, taker_pays: DrcBookAsset, taker_pays_original: bigint, taker_pays_remaining: bigint, taker_gets: DrcBookAsset, taker_gets_original: bigint, taker_gets_remaining: bigint, fill_mode: number, book_sequence: bigint, create_blue_score: bigint, expires_after_blue_score: bigint | null,
/**
 * Native DRC locked out of the spendable balance for the remaining sell.
 */
native_locked: bigint, };
