// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Buy is complete when the taker has acquired `taker_pays`. Sell is complete
 * when the taker has spent `taker_gets`.
 */
export type DrcOfferFillMode = "Buy" | "Sell";
