// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { Hash } from "./Hash";

/**
 * Durable notification emitted after accepting a DRC payment.
 */
export type DrcPaymentOutboxEvent = { payment_id: Hash, from: Address, to: Address, amount: Amount, destination_tag: number, invoice_id: Hash, };
