// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcMultisignAuth } from "./DrcMultisignAuth";
import type { Hash } from "./Hash";

/**
 * Signed account-based DRC payment.
 */
export type DrcPaymentTx = { version: number, from: Address, to: Address, amount: Amount, fee: Amount,
/**
 * Recipient-local routing metadata. `Some(0)` is distinct from no tag in v3.
 */
destination_tag: number | null,
/**
 * Optional sender-local routing metadata. `Some(0)` is distinct from no source tag.
 */
source_tag: number | null,
/**
 * `Hash::ZERO` indicates that the payment is not associated with an invoice.
 */
invoice_id: Hash, nonce: bigint,
/**
 * Inclusive containing-block GHOSTDAG blue-score cutoff. `None` never expires.
 */
last_valid_blue_score: bigint | null, public_key: Array<number>, signature: Array<number>, multisign: DrcMultisignAuth | null, };
