// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { Hash } from "./Hash";

export type DrcPaymentChannelLive = { version: number, channel_id: Hash, owner: Address, destination: Address, destination_tag: number | null, source_tag: number | null, invoice_id: Hash, claim_public_key: Array<number>, settle_delay_blue_scores: bigint, cancel_after_blue_score: bigint | null, total_funded: Amount, cumulative_claimed: Amount, close_finalizable_after: bigint | null, create_blue_score: bigint, };
