// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcPaymentResult } from "./DrcPaymentResult";
import type { Hash } from "./Hash";

/**
 * Root-committed settlement receipt indexed by the canonical signed-envelope id.
 *
 * This type is separate from [`DrcPaymentOutboxEvent`] so the frozen outbox-v1
 * encoding remains unchanged.
 */
export type DrcPaymentReceipt = { version: number, payment_id: Hash, payment_version: number, result: DrcPaymentResult, from: Address, to: Address, requested_amount: Amount, delivered_amount: Amount, fee_paid: Amount, source_tag: number | null, destination_tag: number | null, invoice_id: Hash, last_valid_blue_score: bigint | null, };
