// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "./Hash";

/**
 * Immutable owner schedule-close audit record (keyed by `close_tx_id`).
 */
export type DrcPaymentChannelScheduleEvent = { version: number, channel_id: Hash, close_tx_id: Hash, close_finalizable_after: bigint, application_blue_score: bigint, };
