// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { Hash } from "./Hash";

/**
 * Immutable fund audit record (keyed by `fund_tx_id`).
 */
export type DrcPaymentChannelFundEvent = { version: number, channel_id: Hash, fund_tx_id: Hash, amount: Amount, total_funded_after: Amount, application_blue_score: bigint, };
