// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcAccountSequenceSelector } from "./DrcAccountSequenceSelector";
import type { DrcMultisignAuth } from "./DrcMultisignAuth";
import type { Hash } from "./Hash";

export type DrcPaymentChannelClaimTx = { version: number, submitter: Address, channel_id: Hash, cumulative_authorized: Amount, channel_claim_signature: Array<number>, fee: Amount, nonce: bigint, account_sequence: DrcAccountSequenceSelector | null, public_key: Array<number>, signature: Array<number>, multisign: DrcMultisignAuth | null, };
