// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { Hash } from "./Hash";

/**
 * Immutable claim audit record (keyed by `claim_tx_id`).
 */
export type DrcPaymentChannelClaimEvent = { version: number, channel_id: Hash, claim_tx_id: Hash, cumulative_authorized: Amount, claim_delta: Amount, application_blue_score: bigint, };
