// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contract-free DRC settlement has one outcome: the full requested amount arrived.
 *
 * A partial-delivery variant is intentionally absent. Adding any other result requires
 * a separately versioned receipt and state transition.
 */
export type DrcPaymentResult = "delivered_exact";
