// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcPaymentChannelOutcome } from "./DrcPaymentChannelOutcome";
import type { Hash } from "./Hash";

export type DrcPaymentChannelReceipt = { version: number, channel_id: Hash, outcome: DrcPaymentChannelOutcome, owner: Address, destination: Address, total_funded: Amount, cumulative_claimed: Amount, settlement_blue_score: bigint, settlement_tx_id: Hash, };
