// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { Hash } from "./Hash";

/**
 * Signed account-based DRC payment.
 */
export type DrcPaymentTx = { version: number, from: Address, to: Address, amount: Amount, fee: Amount,
/**
 * `0` indicates that the destination does not require a tag.
 */
destination_tag: number,
/**
 * `Hash::ZERO` indicates that the payment is not associated with an invoice.
 */
invoice_id: Hash, nonce: bigint, public_key: Array<number>, signature: Array<number>, };
