// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcRegularKeyAction } from "./DrcRegularKeyAction";

/**
 * Owner-signed operation that sets, replaces, or clears one regular key.
 */
export type DrcRegularKeyTx = { version: number, 
/**
 * DRC account whose regular key is being changed.
 */
owner: Address, action: DrcRegularKeyAction, 
/**
 * Address derived from `regular_key_public_key` when `action == Set`.
 */
regular_key: Address, 
/**
 * Compressed secp256k1 public key (33 bytes) for `Set`; empty for `Clear`.
 */
regular_key_public_key: Array<number>, fee: Amount, 
/**
 * Shared DRC nonce used by transfers, stake ops, policies, preauths, and payments.
 */
nonce: bigint, public_key: Array<number>, signature: Array<number>, };
