// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Install or remove the single rotatable secondary key for one DRC account.
 */
export type DrcRegularKeyAction = "set" | "clear";
