// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcMultisignAuth } from "./DrcMultisignAuth";
import type { DrcSignerListAction } from "./DrcSignerListAction";
import type { DrcSignerListEntry } from "./DrcSignerListEntry";

/**
 * Owner-signed operation that installs, replaces, or deletes one signer list.
 */
export type DrcSignerListTx = { version: number, owner: Address, action: DrcSignerListAction, quorum: number, entries: Array<DrcSignerListEntry>, fee: Amount, nonce: bigint, public_key: Array<number>, signature: Array<number>, multisign: DrcMultisignAuth | null, };
