// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";

/**
 * Canonical `(signer identity, weight)` entry; list order is by ascending signer address.
 */
export type DrcSignerListEntry = { signer: Address, weight: number, };
