// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { DrcTrustLineIssuerControlAction } from "./DrcTrustLineIssuerControlAction";
import type { Hash } from "./Hash";
import type { IssuedAssetId } from "./IssuedAssetId";

export type DrcTrustLineIssuerControlReceipt = { version: number, control_tx_id: Hash, asset: IssuedAssetId, holder: Address, action: DrcTrustLineIssuerControlAction, settlement_blue_score: bigint, };
