// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcAccountSequenceSelector } from "./DrcAccountSequenceSelector";
import type { DrcMultisignAuth } from "./DrcMultisignAuth";
import type { DrcTrustLineIssuerControlAction } from "./DrcTrustLineIssuerControlAction";
import type { IssuedCurrencyCode } from "./IssuedCurrencyCode";

export type DrcTrustLineIssuerControlTx = { version: number, issuer: Address, holder: Address, currency: IssuedCurrencyCode, action: DrcTrustLineIssuerControlAction, fee: Amount, nonce: bigint, account_sequence: DrcAccountSequenceSelector | null, public_key: Array<number>, signature: Array<number>, multisign: DrcMultisignAuth | null, };
