// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcMultisignAuth } from "./DrcMultisignAuth";

/**
 * Owner-signed creation of exactly one outstanding ticket (nonce-only; never consumes a ticket).
 */
export type DrcTicketCreateTx = { version: number, owner: Address, fee: Amount,
/**
 * Ordinary shared DRC nonce at creation time (must equal current account nonce).
 */
nonce: bigint, public_key: Array<number>, signature: Array<number>, multisign: DrcMultisignAuth | null, };
