// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { DrcAccountSequenceSelector } from "./DrcAccountSequenceSelector";
import type { DrcMultisignAuth } from "./DrcMultisignAuth";
import type { IssuedAmount } from "./IssuedAmount";
import type { IssuedCurrencyCode } from "./IssuedCurrencyCode";

export type DrcTrustLineSetTx = { version: number, holder: Address, issuer: Address, currency: IssuedCurrencyCode, limit: IssuedAmount, fee: Amount, nonce: bigint, account_sequence: DrcAccountSequenceSelector | null, public_key: Array<number>, signature: Array<number>, multisign: DrcMultisignAuth | null, };
