// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckpointBody } from "./CheckpointBody";
import type { CheckpointState } from "./CheckpointState";

/**
 * Aggregated certificate (may be partial until both quorums + PoW).
 */
export type FinalityCertificate = { body: CheckpointBody, state: CheckpointState, pow_work_met: boolean, ovl_signed_stake: bigint, ovl_active_stake: bigint, drc_signed_stake: bigint, drc_active_stake: bigint, };
