// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { CommunityGrantKind } from "./CommunityGrantKind";
import type { CommunityGrantMilestone } from "./CommunityGrantMilestone";
import type { Hash } from "./Hash";
import type { TreasuryId } from "./TreasuryId";

/**
 * Active-hub-coordinator-signed grant registration.
 */
export type GrantRegistration = { version: number, registrar: Address, proposal_id: bigint, treasury: TreasuryId, beneficiary: Address, total: Amount, kind: CommunityGrantKind, milestones: Array<CommunityGrantMilestone>, coi_disclosure_hash: Hash, nonce: bigint, public_key: Array<number>, signature: Array<number>, };
