// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 32-byte digest used for block and transaction identifiers.
 *
 * Stored as a fixed array so DAG indexes can key by value without heap allocation.
 */
export type Hash = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];
