// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Hash } from "./Hash";

/**
 * First-coordinator-signed hub accreditation.
 */
export type HubRegistration = { version: number, public_name: string, classification: string, charter_hash: Hash, coordinators: Array<Address>, treasury_multisig: Address, election_term_epochs: bigint, reporting_interval_epochs: bigint, coi_disclosure_root: Hash, deliverables_root: Hash, accreditation_proposal_id: bigint, nonce: bigint, public_key: Array<number>, signature: Array<number>, };
