// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exact issued-value amount (never mixed with native `Amount` in consensus math).
 */
export type IssuedAmount = bigint;
