// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fixed-width issued currency code (consensus bytes only; no locale strings).
 */
export type IssuedCurrencyCode = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];
