// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { Hash } from "./Hash";
import type { TreasuryId } from "./TreasuryId";

/**
 * Sponsor-signed mission registration. Sponsor must be an active hub coordinator.
 */
export type MissionRegistration = { version: number, sponsor: Address, reward_treasury: TreasuryId, reward: Amount, requirements_hash: Hash, nonce: bigint, public_key: Array<number>, signature: Array<number>, };
