// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical native asset on Agora Trident L1.
 */
export type NativeAssetId = "TLT" | "OVL" | "DRC";
