// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "./Hash";

/**
 * Full network identity used to bind datadirs, signatures, and gossip topics.
 *
 * Two nodes that disagree on any field are on different networks and must not
 * share UTXO state or accept each other's transaction signatures.
 */
export type NetworkFingerprint = { 
/**
 * Stable network label (e.g. `agora-devnet`).
 */
network_name: string, 
/**
 * Numeric magic / network id.
 */
network_id: number, 
/**
 * Genesis block hash for this network.
 */
genesis_hash: Hash, 
/**
 * GHOSTDAG `k` parameter.
 */
ghostdag_k: number, 
/**
 * Absolute max supply in base units.
 */
max_supply: bigint, 
/**
 * Premine allocation in base units.
 */
premine: bigint, 
/**
 * Initial block subsidy in base units.
 */
initial_reward: bigint, 
/**
 * Halving interval in blue-score units.
 */
halving_interval: bigint, };
