// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "./Hash";

/**
 * Reference to a previous transaction output spent by an input.
 */
export type OutPoint = { tx_id: Hash, index: number, };
