// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";

/**
 * Signed account-based OVL value transfer or execution request.
 */
export type OvlExecutionTx = { version: number, from: Address, 
/**
 * `Address::ZERO` is reserved for a future contract-create operation.
 */
to: Address, value: Amount, gas_limit: bigint, max_fee_per_gas: bigint, nonce: bigint, data: Array<number>, public_key: Array<number>, signature: Array<number>, };
