// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OvlWei } from "./OvlWei";

/**
 * Genesis fee-market parameters. The formula is consensus code, not a
 * validator setting. `base_fee_burn_bps` must be 10_000.
 */
export type OvlFeeMarketParams = { version: number, initial_base_fee_wei: OvlWei, gas_limit: bigint, elasticity_multiplier: bigint, base_fee_change_denominator: bigint, base_fee_burn_bps: number, };
