// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Hash } from "./Hash";
import type { PassportCategory } from "./PassportCategory";

/**
 * A contribution claim whose issuer and subject are covered by its signature.
 */
export type PassportAttestation = { version: number, issuer: Address, subject: Address, category: PassportCategory, evidence_hash: Hash, issuer_policy_hash: Hash, issued_epoch: bigint, expires_epoch: bigint | null, nonce: bigint, public_key: Array<number>, signature: Array<number>, };
