// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PassportCategory = "Code" | "Documentation" | "Translation" | "SecurityReport" | "Infrastructure" | "EventHosting" | "Teaching" | "MerchantOnboarding" | "GrantReview" | "GovernanceParticipation" | "Moderation" | "CommunitySupport";
