// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Hash } from "./Hash";
import type { NativeAssetId } from "./NativeAssetId";
import type { StakeOpKind } from "./StakeOpKind";

/**
 * Network-bound signed stake transaction.
 */
export type SignedStakeTx = { version: number, asset: NativeAssetId, kind: StakeOpKind, 
/**
 * Signer / liquid debit account (must match pubkey).
 */
actor: Address, 
/**
 * Bond: operator (= actor). Delegate: target validator. Unbond/Withdraw: operator/owner.
 */
validator: Address, 
/**
 * Bond / Delegate amount; ignored for UnbondSelf / Withdraw (full self-bond / matured).
 */
amount: bigint, 
/**
 * Bond only: 33-byte compressed consensus pubkey.
 */
consensus_pubkey: Array<number>, 
/**
 * Bond only: withdrawal address (receives rewards / unbond credits).
 */
withdrawal: Address, 
/**
 * Bond only: commission in basis points.
 */
commission_bps: number, metadata_hash: Hash, 
/**
 * Actor account nonce (must match current on-chain nonce).
 */
nonce: bigint, public_key: Array<number>, signature: Array<number>, };
