// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TltCovenantInput } from "./TltCovenantInput";
import type { TltCovenantOutput } from "./TltCovenantOutput";

/**
 * Versioned TLT covenant transaction.
 *
 * Admitted on the block's covenant lane, separate from v1 [`crate::Transaction`]
 * bytes. `nonce` stays in the sighash so a signature cannot be replayed by
 * editing it, and [`Self::sighash_preimage_bound`] binds a chain id and genesis.
 */
export type TltCovenantTx = { version: number, inputs: Array<TltCovenantInput>, outputs: Array<TltCovenantOutput>, lock_time: bigint, nonce: bigint, };
