// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutPoint } from "./OutPoint";

/**
 * One covenant input. Sequence is on the wire here; v1 [`crate::TxIn`] has none.
 */
export type TltCovenantInput = { previous_outpoint: OutPoint, sequence: number, script_sig: Array<number>, };
