// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";

/**
 * One covenant output. The live UTXO [`crate::TxOut`] remains value plus address.
 */
export type TltCovenantOutput = { value: Amount, script_pubkey: Array<number>, };
