// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "./Hash";
import type { TxOut } from "./TxOut";

/**
 * Minimal transfer transaction used across consensus, mempool, and RPC.
 *
 * Signature bytes are opaque here so `agora-crypto` owns verification policy.
 */
export type Transaction = { version: number, inputs: Array<Hash>, outputs: Array<TxOut>, nonce: bigint, signature: Array<number>, };
