// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TxIn } from "./TxIn";
import type { TxOut } from "./TxOut";

/**
 * Transfer transaction used across consensus, mempool, and RPC.
 */
export type Transaction = { version: number, inputs: Array<TxIn>, outputs: Array<TxOut>, nonce: bigint, 
/**
 * Compressed secp256k1 public key (33 bytes) once signed; empty when unsigned.
 */
public_key: Array<number>, 
/**
 * Compact ECDSA signature (64 bytes) once signed; empty when unsigned.
 */
signature: Array<number>, };
