// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deterministic outcome of evaluating a transaction against the acceptance layer.
 */
export type TransactionAcceptance = "Accepted" | "ExactDuplicate" | "ConflictLost" | "Invalid";
