// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { NativeAssetId } from "./NativeAssetId";
import type { TreasuryId } from "./TreasuryId";

/**
 * Balance held by a protocol treasury in its fixed native asset.
 */
export type TreasuryBalance = { treasury: TreasuryId, asset: NativeAssetId, balance: Amount, };
