// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Protocol treasury with a fixed native-asset denomination.
 */
export type TreasuryId = "TltSecurity" | "OvlBuilder" | "DrcCommunity";
