// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { Hash } from "./Hash";
import type { TreasuryId } from "./TreasuryId";

/**
 * Controller-signed spend from one protocol treasury. Does not mint.
 */
export type TreasuryDisbursement = { version: number, treasury: TreasuryId, beneficiary: Address, amount: Amount, reason_hash: Hash, authorization_root: Hash, nonce: bigint, public_key: Array<number>, signature: Array<number>, };
