// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of a transaction relative to the acceptance layer.
 *
 * Confirmations and explorer status must use this — never block color alone.
 */
export type TxAcceptanceStatus = "Pending" | "Accepted" | "Rejected";
