// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "./Hash";
import type { TxAcceptanceStatus } from "./TxAcceptanceStatus";

/**
 * Confirmation depth derived from acceptance, not mere blue inclusion.
 */
export type TxConfirmation = { status: TxAcceptanceStatus, 
/**
 * Blue-score of the block that accepted this tx (`0` when not accepted).
 */
accepting_blue_score: bigint, 
/**
 * `tip_blue_score - accepting_blue_score` when accepted; otherwise `0`.
 */
confirmations: bigint, accepting_block: Hash, };
