// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutPoint } from "./OutPoint";

/**
 * Single transaction input.
 */
export type TxIn = { previous_outpoint: OutPoint, };
