// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";

/**
 * Single transaction output.
 */
export type TxOut = { value: Amount, address: Address, };
