// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Amount } from "./Amount";
import type { Hash } from "./Hash";
import type { NativeAssetId } from "./NativeAssetId";

/**
 * Beneficiary-signed claim of vested coins. Does not mint.
 */
export type VestingUnlock = { version: number, asset: NativeAssetId, beneficiary: Address, schedule_id: Hash, amount: Amount, nonce: bigint, public_key: Array<number>, signature: Array<number>, };
