import type { DataPlane } from "./planes.ts";

/**
 * Shared feature descriptors. `plane` is the engine that owns the feature.
 * The other columns say what a device may render and what must stay elsewhere.
 */
export type FeatureDescriptor = {
  id: string;
  title: string;
  plane: DataPlane;
  device: string | null;
  infrastructure: string | null;
  onChain: string | null;
  /** This record must not be written as consensus state. */
  onChainForbidden: boolean;
  trust: string | null;
};

export const DATA_PLANE_FEATURES: readonly FeatureDescriptor[] = [
  {
    id: "wallet",
    title: "Wallet",
    plane: "device",
    device: "BIP-39 vault, secp256k1 signing, and addresses stay on the PC or phone.",
    infrastructure: null,
    onChain: null,
    onChainForbidden: false,
    trust: null,
  },
  {
    id: "light-verification",
    title: "Light verification",
    plane: "device",
    device: "Header hashes, selected-parent links, TLT Merkle inclusion, and quorum arithmetic are recomputed on the device.",
    infrastructure: null,
    onChain: null,
    onChainForbidden: false,
    trust: "A light client still trusts one full node for GHOSTDAG parent selection, RandomX work, and validator signatures.",
  },
  {
    id: "passport-ui",
    title: "Passport UI",
    plane: "device",
    device: "Shows a public passport and keeps email and language off the ledger.",
    infrastructure: "Optional authenticated profile store. The app does not host that store.",
    onChain: "A passport attestation is a separate credential, and only when one is actually signed.",
    onChainForbidden: false,
    trust: null,
  },
  {
    id: "community-ui",
    title: "Community UI",
    plane: "device",
    device: "Renders directories, hubs, and posts returned by HTTP.",
    infrastructure: "Community directory and forum live in infrastructure.",
    onChain: null,
    onChainForbidden: false,
    trust: null,
  },
  {
    id: "drc-payments",
    title: "DRC payments",
    plane: "device",
    device: "Payment QR, destination, amount, and local signing.",
    infrastructure: null,
    onChain: "A real DrcPaymentTx is consensus. This client does not submit a look-alike.",
    onChainForbidden: false,
    trust: null,
  },
  {
    id: "qr",
    title: "QR",
    plane: "device",
    device: "Encodes and parses versioned Agora QR payloads on the device.",
    infrastructure: null,
    onChain: null,
    onChainForbidden: false,
    trust: null,
  },
  {
    id: "missions-ui",
    title: "Missions UI",
    plane: "device",
    device: "Lists missions. It does not record reviews or payouts.",
    infrastructure: "Grant and mission management accepts transitions.",
    onChain: null,
    onChainForbidden: false,
    trust: null,
  },
  {
    id: "academy-ui",
    title: "Academy UI",
    plane: "device",
    device: "Shows courses. Lesson progress stays on the device.",
    infrastructure: "Course catalog may be served by infrastructure.",
    onChain: null,
    onChainForbidden: false,
    trust: null,
  },
  {
    id: "governance-ui",
    title: "Governance UI",
    plane: "device",
    device: "Shows areas, eligibility, and advisory polls.",
    infrastructure: "Advisory polls are community records.",
    onChain: "A governance transaction counts only when a full node committed it.",
    onChainForbidden: false,
    trust: "An indexed commitment id is not a validator-signature proof.",
  },
  {
    id: "merchant-tools",
    title: "Merchant tools",
    plane: "device",
    device: "Invoice and receiving-address tools. Merchant spend keys are not stored.",
    infrastructure: "Merchant directory is infrastructure.",
    onChain: null,
    onChainForbidden: false,
    trust: null,
  },
  {
    id: "notifications-ui",
    title: "Notifications UI",
    plane: "device",
    device: "Preferences and display. Push copy strips amounts.",
    infrastructure: "The dispatcher runs off the device. The app may register a token over HTTP.",
    onChain: null,
    onChainForbidden: false,
    trust: "The operator sees the registration. The device does not run the send loop.",
  },
  {
    id: "explorer-ui",
    title: "Explorer UI",
    plane: "device",
    device: "Renders blocks, transactions, and mempool rows from a full node.",
    infrastructure: "An indexer is optional and is not embedded in the explorer bundle.",
    onChain: "Canonical rows come from the node, not from a fabricated index.",
    onChainForbidden: false,
    trust: "Explorer figures are node-reported unless a light proof is recomputed.",
  },
  {
    id: "guilds-ui",
    title: "Guilds UI",
    plane: "device",
    device: "Renders guild charters returned by HTTP.",
    infrastructure: "Guild membership records are infrastructure.",
    onChain: null,
    onChainForbidden: false,
    trust: null,
  },
  {
    id: "indexer",
    title: "Indexing",
    plane: "infrastructure",
    device: "May ask the indexer whether it has an upstream. It must not import the indexer.",
    infrastructure: "Operator-run index in infrastructure/indexer.",
    onChain: null,
    onChainForbidden: false,
    trust: "The indexer is not a second consensus and not a light-client proof. chainProof is always false. With no upstream full node it returns no chain rows.",
  },
  {
    id: "forum-backend",
    title: "Forum backend",
    plane: "infrastructure",
    device: "Forum UI calls HTTP. It does not import forum-server.",
    infrastructure: "infrastructure/forum-server stores posts.",
    onChain: null,
    onChainForbidden: false,
    trust: "The operator can omit, reorder, or alter posts. Posts are not votes and not treasury spends.",
  },
  {
    id: "grant-mission-admin",
    title: "Grant and mission management",
    plane: "infrastructure",
    device: "The missions screen lists and submits. It does not host the admin engine.",
    infrastructure: "infrastructure/grant-admin records grants, missions, and reviews.",
    onChain: null,
    onChainForbidden: false,
    trust: "Admin records do not move treasury funds. A review is not a consensus receipt.",
  },
  {
    id: "event-service",
    title: "Event services",
    plane: "infrastructure",
    device: "Events UI lists rows. It does not run the event service.",
    infrastructure: "infrastructure/event-service.",
    onChain: null,
    onChainForbidden: false,
    trust: "Event times and venues are operator-hosted records.",
  },
  {
    id: "notification-dispatch",
    title: "Notification dispatch",
    plane: "infrastructure",
    device: "The app registers a token. It does not run the dispatcher.",
    infrastructure: "infrastructure/notification-dispatch queues sends.",
    onChain: null,
    onChainForbidden: false,
    trust: "Dispatch payloads must not carry amounts or balances. The operator can drop or delay a notice.",
  },
  {
    id: "search",
    title: "Search",
    plane: "infrastructure",
    device: "A typed hub filter on data the device already holds is UI. The search engine is not in the app.",
    infrastructure: "infrastructure/search.",
    onChain: null,
    onChainForbidden: false,
    trust: "Search hits are the operator's index of community documents, not chain state.",
  },
  {
    id: "moderation",
    title: "Moderation",
    plane: "infrastructure",
    device: "Report buttons POST to the moderation service.",
    infrastructure: "infrastructure/moderation.",
    onChain: null,
    onChainForbidden: false,
    trust: "A report is an operator queue item. It does not change reputation or consensus.",
  },
  {
    id: "tlt-balances-txs",
    title: "TLT balances and transactions",
    plane: "on-chain",
    device: "Reads UTXOs and history from a full node and verifies TLT inclusion locally when a proof is present.",
    infrastructure: null,
    onChain: "TLT UTXOs, spends, and coinbase.",
    onChainForbidden: false,
    trust: "Balances are node-reported until a header proof covers them.",
  },
  {
    id: "ovl-balances-txs",
    title: "OVL balances and transactions",
    plane: "on-chain",
    device: "Signs account transfers on the device and reads balances from the node.",
    infrastructure: null,
    onChain: "OVL account balances, nonces, and execution transactions.",
    onChainForbidden: false,
    trust: "OVL balances are not proven against a state root in the live header.",
  },
  {
    id: "drc-balances-txs",
    title: "DRC balances and transactions",
    plane: "on-chain",
    device: "Builds typed DRC envelopes on the device when the signer is present.",
    infrastructure: null,
    onChain: "DRC account balances and typed payment transactions.",
    onChainForbidden: false,
    trust: "DRC ledger objects are state, not BlockHeader.tx_root. A missing proof fails closed.",
  },
  {
    id: "governance-txs",
    title: "Governance transactions",
    plane: "on-chain",
    device: "Shows a commitment only when the node reported one.",
    infrastructure: "Advisory polls stay off chain.",
    onChain: "Governance transactions that a full node actually committed.",
    onChainForbidden: false,
    trust: "A poll without a commitment id stays advisory. The light client does not check validator signatures.",
  },
  {
    id: "treasury-txs",
    title: "Treasury transactions",
    plane: "on-chain",
    device: "Displays agora_getProtocolTreasuries. It does not fill missing rows.",
    infrastructure: null,
    onChain: "Protocol treasury balances and treasury transactions.",
    onChainForbidden: false,
    trust: "A full-node treasury read is not an infrastructure index and not a header proof. Unsigned civic RPC cannot spend it.",
  },
  {
    id: "credential-attestations",
    title: "Verifiable credentials and attestations",
    plane: "on-chain",
    device: "May display an attestation the node already committed.",
    infrastructure: null,
    onChain: "secp256k1 passport attestations and other credentials only when a specific attestation is justified.",
    onChainForbidden: false,
    trust: "An attestation is contribution evidence. It is not personhood and not a transferable token.",
  },
  {
    id: "private-profile",
    title: "Private profile",
    plane: "device",
    device: "Email and language stay on the device unless an authenticated service holds them.",
    infrastructure: "Optional authenticated profile store.",
    onChain: null,
    onChainForbidden: true,
    trust: "Private profile fields are not consensus. consensus stays false.",
  },
  {
    id: "forum-posts",
    title: "Forum posts",
    plane: "infrastructure",
    device: "Rendered by the community UI.",
    infrastructure: "Stored by the forum server.",
    onChain: null,
    onChainForbidden: true,
    trust: "Posts are not chain transactions. Existing administrative civic forum RPC is local node state, not this plane and not a device embed.",
  },
  {
    id: "mission-reviews",
    title: "Mission reviews",
    plane: "infrastructure",
    device: "The missions screen does not store review notes.",
    infrastructure: "Reviews stay in grant and mission management.",
    onChain: null,
    onChainForbidden: true,
    trust: "A review does not pay a treasury and is not a receipt.",
  },
  {
    id: "academy-progress",
    title: "Academy progress",
    plane: "device",
    device: "Completed lesson ids stay in device storage.",
    infrastructure: null,
    onChain: null,
    onChainForbidden: true,
    trust: "Progress is not an academy certificate. A certificate would be a separate attestation.",
  },
];

export function featureById(id: string): FeatureDescriptor {
  const row = DATA_PLANE_FEATURES.find((feature) => feature.id === id);
  if (!row) throw new Error(`unknown data-plane feature ${id}`);
  return row;
}
